### ISSUE TITLE
[ERROR] Unable to find binary radamsa required to run Manul

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [mxmssh/manul#42]
Hello I had an error about the radamsa not being installed for the linux version. I installed in the same path and got the same error. 

Fix: 

instead of 

# if radamsa weight is not zero, check that we can actually execute it
    if "radamsa:0" not in args.mutator_weights:
        if sys.platform == "win32":
            check_binary("radamsa.exe")
        else:
            check_binary("radamsa")

tried this 

# if radamsa weight is not zero, check that we can actually execute it
    if "radamsa:0" not in args.mutator_weights:
        if sys.platform == "win32":
            check_binary("radamsa.exe")
        else:
            check_binary("./radamsa")

However flowing the commands to install radamsa 

git clone https://gitlab.com/akihe/radamsa.git && cd radamsa && make && sudo make install

solved it

**Comment by mxmssh** [comment]
Thanks for pointing out that. In the next release, Radamsa will be integrated as a library, so you will not need worry about that :)

**Comment by KittyTechnoProgrammer** [comment]
Alright then. Thank you for responding, and taking time to help. Don't know where. Don't know when, but I know we'll meet again some sunny day.
