### ISSUE TITLE
windows issues

### ISSUE THREAD

**Issue by b0q1** [mxmssh/manul#50]
bin_coverage.c:328:false (error accessing__AFL_SHM_ID)

**Comment by mxmssh** [comment]
I see that you have some problems with SHM but could you provide more details associated with this bug?

**Comment by b0q1** [comment]
D:\manul>python manul.py -i in -o out "fuzztest.exe @@"
[WARNING] Output directory is not empty, creating backup of output folder
[INFO] Done
[INFO] 1 fuzzer instances successfully launched
[INFO] Starting fuzzer 0
[INFO] Setting up shared mem 1579231410_0 for fuzzer:0
[INFO] Initializing mutators
[INFO] Performing dry run
[INFO] Sending SIGKILL signal to 15408 cmd.exe

and msg：
ASSERT FAILURE:
C:\Users\max\Desktop\manul\bin_cov\bin_coverage.c:328:false (error accessing__AFL_SHM_ID)

manul.config:
dbi = dynamorio
dbi_root = C:\\winafl\\DynamoRIO\\bin32\\drrun.exe
dbi_client_root = D:\\manul\\win\\dbi_32\\binafl.dll
dbi_client_libs = FreeImage.dll

**Comment by b0q1** [comment]
maybe “bin_coverage” can't get shared memory

**Comment by mxmssh** [comment]
hm, weird. Does your target a 32-bit binary?
