### ISSUE TITLE
real path of input file

### ISSUE THREAD

**Issue by jplopezy** [mxmssh/manul#66]
Hello!

I have a question about how put the realname of input file ("for example afl allow put -f" )

I'm trying to do something like this ( on windows 10 with de dumb mode)

manul.py -i C:\Users\test\Downloads\manul-master\in -o C:\Users\test\Downloads\manul-master\out  -n 1  -s  "mspaint.exe @@" 

but in the process montitor show "C:\Users\test\Downloads\manul-master\out\0\mutations\.cur_input"

regards

**Comment by Max414141** [comment]
There is no such feature for Manul but I will add it on the list of required features.

**Comment by mxmssh** [comment]
There is no such option for Manul at the moment. It will be implemented in the future releases.

**Comment by jplopezy** [comment]
Thanks so much, one question and about paths with some white space how i
can skip it

Like.


 "C:\Program Files (x86)\program\@@"

**Comment by mxmssh** [comment]
Could you please provide a full example of what you are trying to  execute?

**Comment by jplopezy** [comment]
Yes sure, i 'm trying to fuzz Kaspersky so the full path is

"C:\Program Files (x86)\Kaspersky Lab\Kaspersky Internet Security
20.0\avp.exe"

but i'm getting an error because fail to parse this path


[image: imagen.png]
regards

**Comment by jplopezy** [comment]
C:\Users\test\Downloads\manul-master>manul.py -i in -o out -n 5 "C:\Program
Files (x86)\Kaspersky Lab\Kaspersky Internet Security 20.0\avp.exe SCAN @@"
[ERROR] Unable to find binary C:Program (required)

**Comment by mxmssh** [comment]
It seems like a problem with path parsing when it has spaces. You can add ```--skip_binary_check``` to be able to start fuzzing. Please don't forget that your target need to be instrumented or you need to run manul in dumb mode (```-s``` option).

**Comment by mxmssh** [comment]
You need to pull the latest version of Manul. I just fixed it.
